name: Build Unity Project🧪

#####################################################################################
# Please be mindful when running this workflow, as it spins up quite a few runners. #
#####################################################################################

on:
  workflow_dispatch: 
    inputs:
      targetPlatform:
        description: 'Target Platform'
        required: true
        default: 'WebGL'
        type: choice
        options:
          - WebGL
          - StandaloneWindows64
          - StandaloneLinux64
      runsOnServer:
        description: 'Runner Server'
        required: true
        default: 'self-hosted'
        type: choice
        options:
          - self-hosted
          - ubuntu-latest
jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ${{ inputs.runsOnServer }} 
    strategy:
            fail-fast: false
            matrix:
                targetPlatform: 
                 - ${{ inputs.targetPlatform }} 
                
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      # Test
  #     - name: Run tests
  #      uses: game-ci/unity-test-runner@v4
  #      env:
  #        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  #        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  #      with:
  #       githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: BuildBuild-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
